function getLogos() {
  var logos = new Map();
  logos.set('Walmart', 'https://logo.clearbit.com/walmart.com');
  logos.set('Visa', 'https://logo.clearbit.com/visa.com');
  logos.set('Apple', 'https://logo.clearbit.com/apple.com');
  logos.set('Dominos', 'https://logo.clearbit.com/dominos.com');
  logos.set('Amazon', 'https://logo.clearbit.com/amazon.com');
  logos.set('Pizza Hut', 'https://logo.clearbit.com/pizzahut.com');
  logos.set('Zara', 'https://logo.clearbit.com/zara.com');
  logos.set('ICICI Bank', 'https://logo.clearbit.com/icicibank.com');
  logos.set('AT&T', 'https://logo.clearbit.com/att.com');
  logos.set('Bharat Pe', 'https://logo.clearbit.com/bharatpe.com');
  logos.set('Chevron', 'https://logo.clearbit.com/chevron.com');
  logos.set('Ford Motors', 'https://logo.clearbit.com/ford.com');
  logos.set('TATA', 'https://logo.clearbit.com/tata.com');
  logos.set('SBI', 'https://logo.clearbit.com/statebankofindia.com');
  logos.set('DuckDuckGo', 'https://logo.clearbit.com/duckduckgo.com');
  logos.set('Jio', 'https://logo.clearbit.com/jio.com');
  logos.set('Walgreens', 'https://logo.clearbit.com/walgreens.com');
  logos.set('JPMorgan Chase', 'https://logo.clearbit.com/jpmorganchase.com');
  logos.set('Google', 'https://logo.clearbit.com/google.com');
  logos.set('Sony', 'https://logo.clearbit.com/sony.com');
  logos.set('General Electric', 'https://logo.clearbit.com/ge.com');
  logos.set('Starbucks', 'https://logo.clearbit.com/starbucks.com');
  logos.set('IKEA', 'https://logo.clearbit.com/ikea.com');
  logos.set('NASA', 'https://logo.clearbit.com/nasa.gov');
  logos.set('Ferrari', 'https://logo.clearbit.com/ferrari.com');
  logos.set('Microsoft', 'https://logo.clearbit.com/microsoft.com');
  logos.set('Home Depot', 'https://logo.clearbit.com/homedepot.com');
  logos.set('Boeing', 'https://logo.clearbit.com/boeing.com');
  logos.set('Wells Fargo', 'https://logo.clearbit.com/wellsfargo.com');
  logos.set('Citigroup', 'https://logo.clearbit.com/citigroup.com');
  logos.set('KFC', 'https://logo.clearbit.com/kfc.com');
  logos.set('Honda', 'https://logo.clearbit.com/honda.com');
  logos.set('British Petroleum', 'https://logo.clearbit.com/bp.com');
  logos.set('Dell', 'https://logo.clearbit.com/delltechnologies.com');
  logos.set('Lego', 'https://logo.clearbit.com/lego.com');
  logos.set('Indigo Airlines', 'https://logo.clearbit.com/goindigo.in');
  logos.set('Johnson & Johnson', 'https://logo.clearbit.com/jnj.com');
  logos.set('IBM', 'https://logo.clearbit.com/ibm.com');
  logos.set('Target', 'https://logo.clearbit.com/target.com');
  logos.set('NBC', 'https://logo.clearbit.com/nbc.com');
  logos.set('United Parcel Service', 'https://logo.clearbit.com/ups.com');
  logos.set('Suzuki', 'https://logo.clearbit.com/Suzuki.com');
  logos.set('Intel', 'https://logo.clearbit.com/intel.com');
  logos.set('MetLife', 'https://logo.clearbit.com/metlife.com');
  logos.set('Procter & Gamble', 'https://logo.clearbit.com/pg.com');
  logos.set('Big Basket', 'https://logo.clearbit.com/bigbasket.com');
  logos.set('FedEx', 'https://logo.clearbit.com/fedex.com');
  logos.set('WeChat', 'https://logo.clearbit.com/wechat.com');
  logos.set('HSBC', 'https://logo.clearbit.com/hsbc.com');
  logos.set('JBL Audio', 'https://logo.clearbit.com/jbl.com');
  logos.set('H & M', 'https://logo.clearbit.com/hm.com');
  logos.set('Chase', 'https://logo.clearbit.com/chase.com');
  logos.set('Disney', 'https://logo.clearbit.com/disney.com');
  logos.set('Louis Vuitton', 'https://logo.clearbit.com/louisvuitton.com');
  logos.set('HP', 'https://logo.clearbit.com/hp.com');
  logos.set('Paytm', 'https://logo.clearbit.com/paytm.com');
  logos.set('Facebook', 'https://logo.clearbit.com/facebook.com');
  logos.set('Caterpillar', 'https://logo.clearbit.com/caterpillar.com');
  logos.set('Vodafone', 'https://logo.clearbit.com/vodafone.com');
  logos.set('Nestle', 'https://logo.clearbit.com/nestle.com');
  logos.set('Pfizer', 'https://logo.clearbit.com/pfizer.com');
  logos.set('Goldman Sachs Group', 'https://logo.clearbit.com/gs.com');
  logos.set('Volkswagen', 'https://logo.clearbit.com/volkswagen.com');
  logos.set('Cisco Systems', 'https://logo.clearbit.com/cisco.com');
  logos.set('Cigna', 'https://logo.clearbit.com/cigna.com');
  logos.set('AIG', 'https://logo.clearbit.com/aig.com');
  logos.set('JetBlue Airlines', 'https://logo.clearbit.com/jetblue.com');
  logos.set('Spicejet', 'https://logo.clearbit.com/spicejet.com');
  logos.set('Delta Airlines', 'https://logo.clearbit.com/delta.com');
  logos.set('Airtel', 'https://logo.clearbit.com/airtel.in');
  logos.set('New York Life Insurance', 'https://logo.clearbit.com/newyorklife.com');
  logos.set('American Express', 'https://logo.clearbit.com/americanexpress.com');
  logos.set('Nationwide', 'https://logo.clearbit.com/nationwide.com');
  logos.set('Best Buy', 'https://logo.clearbit.com/bestbuy.com');
  logos.set('LG', 'https://logo.clearbit.com/lg.com');
  logos.set('Morris Garage', 'https://logo.clearbit.com/mg.co.uk');
  logos.set('Honeywell International', 'https://logo.clearbit.com/honeywell.com');
  logos.set('United Airlines', 'https://logo.clearbit.com/united.com');
  logos.set('IBM', 'https://logo.clearbit.com/ibm.com');
  logos.set('Nikon', 'https://logo.clearbit.com/nikon.com');
  logos.set('Oracle', 'https://logo.clearbit.com/oracle.com');
  logos.set('Tesla', 'https://logo.clearbit.com/tesla.com');
  logos.set('Lenovo', 'https://logo.clearbit.com/lenovo.com');
  logos.set('Whole Foods', 'https://logo.clearbit.com/wholefoods.com');
  logos.set('Shell', 'https://logo.clearbit.com/shell.com');
  logos.set('Reliance', 'https://logo.clearbit.com/ril.com');
  logos.set('John Deere', 'https://logo.clearbit.com/johndeere.com');
  logos.set('Burger King', 'https://logo.clearbit.com/burgerking.com');
  logos.set('UBS', 'https://logo.clearbit.com/ubs.com');
  logos.set('Nike', 'https://logo.clearbit.com/nike.com');
  logos.set('Target', 'https://logo.clearbit.com/target.com');
  logos.set('Jaguar', 'https://logo.clearbit.com/jaguar.com');
  logos.set('Jeep', 'https://logo.clearbit.com/jeep.com');
  logos.set('Mastercard', 'https://logo.clearbit.com/mastercard.com');
  logos.set('3M', 'https://logo.clearbit.com/3m.com');
  logos.set('McDonalds', 'https://logo.clearbit.com/mcdonalds.com');
  logos.set('LinkedIn', 'https://logo.clearbit.com/linkedin.com');
  logos.set('Capital One Financial', 'https://logo.clearbit.com/capitalone.com');
  logos.set('Honda', 'https://logo.clearbit.com/honda.com');
  logos.set('Coca-Cola', 'https://logo.clearbit.com/coca-colacompany.com');
  return logos;
}

module.exports = { getLogos };
